version: "3"
services:
  redis:
    image: redis
  datahub-fe:
    env_file:
     - .env
    build:
      context: .
    ports:
      - 3000:3000
      - 9229:9229
    environment:
     - API_ROOT
     - API_CLIENT_ID
     - API_CLIENT_SECRET
     - POSTCODE_KEY
    volumes:
      - ./assets:/usr/src/app/assets
      - ./common:/usr/src/app/common
      - ./config:/usr/src/app/config
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    command: ./node_modules/.bin/nodemon $NODE_DEBUG_OPTION --inspect -L
    links:
      - redis
  webpack:
    build:
      context: .
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - WEBPACK_ENV="docker"
    volumes:
      - ./assets:/usr/src/app/assets
      - ./common:/usr/src/app/common
      - ./config:/usr/src/app/config
    command: ./node_modules/.bin/webpack --watch --watch-poll --progress
    links:
      - datahub-fe
